sudo: required
services: 
    - docker

before_install: 
    - docker build -t hicofish/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true hicofish/docker-react npm run test -- --coverage
